Document: pacman-buildscripts
Title: Debian pacman-buildscripts Manual
Author: <insert document author here>
Abstract: This manual describes what pacman-buildscripts is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pacman-buildscripts/pacman-buildscripts.sgml.gz

Format: postscript
Files: /usr/share/doc/pacman-buildscripts/pacman-buildscripts.ps.gz

Format: text
Files: /usr/share/doc/pacman-buildscripts/pacman-buildscripts.text.gz

Format: HTML
Index: /usr/share/doc/pacman-buildscripts/html/index.html
Files: /usr/share/doc/pacman-buildscripts/html/*.html
